### ISSUE TITLE
I can't find correct parameters in the config.yaml file

### ISSUE THREAD

**Issue by sanba06c** [axon-git/DeleFriend#9]
Hello,

Following the section "Configure the GCP access token and target workspace user in the config.yaml file", I did not find any parameters corresponding to "access_token" or "workspace user" in the said file:

![SCR-20231205-jjtx](https://github.com/axon-git/DeleFriend/assets/50707540/fe1ffccb-e84c-4280-9107-85b810924f37)

Hope that you can clarify this.

Thanks.

**Comment by yonatankhunters** [comment]
Hey!
The access token is the programmatic way to authenticate with the tested IAM user. You can get it in various ways, the simplest would be to run `gcloud auth print-access-token` in the context of the relevant user. The `workspace_user_email` is a target workspace user in your organization, per our research **any** user can be used. Also, automatic functionality helps you find workspace users, so this parameter is optional.

I recommend taking a look at our research paper post, it delves into each of those concepts  https://www.hunters.security/en/blog/delefriend-a-newly-discovered-design-flaw-in-domain-wide-delegation-could-leave-google-workspace-vulnerable-for-takeover

**Comment by sanba06c** [comment]
> Hey! The access token is the programmatic way to authenticate with the tested IAM user. You can get it in various ways, the simplest would be to run `gcloud auth print-access-token` in the context of the relevant user. The `workspace_user_email` is a target workspace user in your organization, per our research **any** user can be used. Also, automatic functionality helps you find workspace users, so this parameter is optional.
> 
> I recommend taking a look at our research paper post, it delves into each of those concepts https://www.hunters.security/en/blog/delefriend-a-newly-discovered-design-flaw-in-domain-wide-delegation-could-leave-google-workspace-vulnerable-for-takeover

Sorry for any misunderstanding, but I originally meaned which parameters should I input in the "config.yaml" file. On closer look, I assume that it should be put under IAMUserAccessKey. Appreciate your detailed article, which I've been reading and following so far.
